apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-sidecar-config
  namespace: tomcat
  labels:
    app: tomcat-app
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
    @INCLUDE input-java.conf
    @INCLUDE input-tomcat-accesslog.conf
    @INCLUDE filter-stdout.conf
    @INCLUDE output-stdout.conf
  input-java.conf: |
    [INPUT]
        Name              tail
        Tag               tomcat
        Path              /mnt/log/*.log
        Multiline        On
        Parser_Firstline java_multiline
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-tomcat-accesslog.conf: |
    [INPUT]
        Name              tail
        Tag               tomcatal
        Path              /mnt/log/*.txt
        Parser            apache2
        DB                /var/log/flb_accesslog.db
        Mem_Buf_Limit     5MB
        Refresh_Interval  10
  filter-stdout.conf: |
    [FILTER]
        Name           stdout
        Match            *
  output-stdout.conf: |
    [OUTPUT]
        Name           null
        Match           *
  parsers.conf: |
    [PARSER]
        Name        java_multiline
        Format      regex
        Regex       /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S

    [PARSER]
        Name        apache2
        Format      regex
        Regex       ^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s-\s-\s\[(\d{2}/[a-zA-Z]{3}/\d{4}):(\d{2}:\d{2}:\d{2}\s[+-]\d{4})\]\s"([A-Z]+)\s(.*?)\s(HTTP/\d\.\d)"\s(\d{3})\s(\d+)$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z
        
# https://kubernetes.io/docs/concepts/configuration/configmap/
immutable: true
