apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-loadbalancer
  namespace: tomcat
spec:
  type: LoadBalancer
  selector:
    app: tomcat-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
